package parker.core.runtime

import java.time.Instant
import java.util.UUID
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import parker.core.interfaces.EventBus
import parker.core.interfaces.EventType
import parker.core.interfaces.IdentityService
import parker.core.interfaces.ParkerEvent
import parker.core.interfaces.PlanCandidate
import parker.core.interfaces.PlanDecision
import parker.core.interfaces.PlanDecisionResult
import parker.core.interfaces.PlannerRuntime
import parker.core.interfaces.PlannerSessionLifecycleTransitions
import parker.core.interfaces.PlannerSessionStatus
import parker.core.interfaces.PlanningRequest
import parker.core.interfaces.PlanningSessionId
import parker.core.interfaces.PlanningSessionResult
import parker.core.interfaces.PlanRejection
import parker.core.interfaces.PrincipalId
import parker.core.interfaces.TaskProposal
import parker.core.interfaces.TaskProposalDisposition
import parker.core.interfaces.TaskProposalId
import parker.core.interfaces.TaskProposalIntake

/**
 * Sprint 3, Track D, Unit D2 (Alignment Pass). The Planner Runtime
 * progression `docs/architecture/PLANNER_RUNTIME_PROGRESSION_DESIGN.md`
 * Section 11 asks Unit D2 to build: Plan Candidates -> [PlanDecision] ->
 * Task Proposal -> [TaskProposalIntake.submitProposal], driving
 * `PlannerRuntimeSpecification.md` Section 5's lifecycle through the
 * subset [PlannerSessionLifecycleTransitions] documents, now implementing
 * the [PlannerRuntime] interface `docs/architecture/PLANNER_RUNTIME_CONTRACT_DESIGN.md`
 * §10/§11 approved.
 *
 * This is a **new, separate production implementation** -- not a
 * relocation of `DeterministicPlannerHarness.kt` (test-only, `tests/`,
 * exactly one fixed candidate, never calls
 * `TaskProposalIntake.submitProposal`), per the design document's Section
 * 11 explicit instruction that Unit D2 must not promote that fixture.
 * Named `InMemoryPlannerRuntime` for consistency with
 * [InMemoryTaskManagerRuntime] and [InMemoryAgentRuntime]'s own identical
 * "in-memory, explicitly scoped, production-quality precedent" naming --
 * and, as of this Alignment Pass, following the same "implements a
 * pre-existing interface" pattern those two classes already establish
 * (`InMemoryTaskManagerRuntime : TaskProposalIntake`,
 * `InMemoryAgentRuntime : AgentRunCommandChannel`), via `: PlannerRuntime`
 * below.
 *
 * ## Scope: what this does and does not do
 *
 * **Candidate generation is not this class's job.** [PlanCandidate]s
 * arrive already-formed, as [plan]'s own `candidates` parameter -- this
 * class only progresses a Planning Session through Plan Decision, Task
 * Proposal construction, and submission. This mirrors the design
 * document's own exclusion of "Planner reasoning" and "LLM integration."
 * Per `PLANNER_RUNTIME_CONTRACT_DESIGN.md` §6, `candidates` is a separate
 * parameter to [plan], not a field of [PlanningRequest] -- candidates are
 * generated by planning, not supplied by callers alongside the request
 * that starts it.
 *
 * **Exactly one Task Proposal per Planning Session.** The single selected
 * [PlanCandidate] becomes exactly one [TaskProposal] -- Section 6's "one
 * or more Task Proposals" is not fully realised; splitting one Planning
 * Session's output into several Task Proposals is out of this Unit's
 * scope (no "Multi-agent planning"/"Resource optimisation").
 *
 * **`WAITING_FOR_INPUT` and `CANCELLED` are not reached.** See
 * [PlannerSessionStatus]'s own KDoc for exactly why, and why this is a
 * documented coverage gap, not a specification defect.
 *
 * **Deferred/Split/Merged disposition handling is not implemented, but is
 * still correctly classified.** [TaskProposalIntake.submitProposal] may,
 * per its own five-outcome contract, return `Deferred`, `Split`, or
 * `Merged` -- this class does not implement any decision logic for those
 * outcomes (that remains `InMemoryTaskManagerRuntime`'s own, separately
 * tracked, "accept-only" scope), but per
 * `PlannerRuntimeSpecification.md` Section 5 ("COMPLETED... any outcome
 * other than every proposal being rejected outright"), this class still
 * correctly transitions the Planning Session to `COMPLETED` for any of
 * them, exactly as it would for `Accepted`. Reading and classifying an
 * already-returned disposition value is not the same as implementing the
 * disposition mechanism itself.
 *
 * ## Concurrency
 *
 * A single [Mutex] guards only the `sessions` map (duplicate-submission
 * detection and status bookkeeping), never held across a `suspend` call
 * to another component ([identityService], [eventBus], [planDecision], or
 * [taskProposalIntake]) -- the same discipline
 * [InMemoryTaskManagerRuntime] and [InMemoryAgentRuntime] already
 * establish. No general-purpose concurrency model for multiple
 * simultaneous Planning Sessions is introduced beyond this -- the design
 * document's own Section 8 recommends, but does not require, this
 * precedent be followed, and this class follows it without adding
 * anything further.
 */
class InMemoryPlannerRuntime(
    private val identityService: IdentityService,
    private val eventBus: EventBus,
    private val taskProposalIntake: TaskProposalIntake,
    private val planDecision: PlanDecision = DefaultPlanDecision(),
) : PlannerRuntime {

    private companion object {
        /** Sprint 1 placeholder pattern, matching [DeterministicPlannerHarness]'s own `PLANNER_RUNTIME_PRINCIPAL_ID`. */
        val PLANNER_RUNTIME_PRINCIPAL_ID = PrincipalId("system.planner-runtime")
    }

    private val mutex = Mutex()
    private val sessions = mutableMapOf<PlanningSessionId, PlannerSessionStatus>()

    /**
     * The current [PlannerSessionStatus] for [planningSessionId], or
     * `null` if it was never submitted, or if its initiating Principal
     * never resolved -- see [plan]'s own KDoc for why the latter case
     * leaves no record at all. Not part of the [PlannerRuntime] interface
     * -- an implementation-specific inspection method, mirroring
     * [InMemoryTaskManagerRuntime.getTask]/[InMemoryAgentRuntime.getAgentRun]'s
     * identical "observability method, not part of the formal interface"
     * precedent.
     */
    suspend fun getSessionStatus(planningSessionId: PlanningSessionId): PlannerSessionStatus? =
        mutex.withLock { sessions[planningSessionId] }

    /**
     * Runs one Planning Session to a terminal [PlanningSessionResult]:
     * `CREATED -> CONTEXT_GATHERING -> ANALYSING -> ` then either
     * `FAILED` (no viable [PlanCandidate]) or
     * `PROPOSING -> SUBMITTED -> {COMPLETED, REJECTED}` (a [PlanCandidate]
     * was selected and submitted).
     *
     * **Identity is resolved *before* `CREATED`.**
     * `PlannerRuntimeSpecification.md` Section 8: "No Planning Session may
     * leave `CREATED` ... without a resolvable `PrincipalId`." Section 5's
     * own diagram has no `CREATED -> FAILED` edge (only
     * `CONTEXT_GATHERING`/`CANCELLED`), so an unresolvable
     * [PlanningRequest.initiatingPrincipalId] is deliberately **not**
     * modelled as a lifecycle transition at all: no session record is
     * ever created, no `planner.session_created` event is ever published,
     * and [getSessionStatus] returns `null` afterward -- mirroring
     * [InMemoryTaskManagerRuntime]'s own unresolvable-owner precedent
     * exactly ("no Task record is ever created there").
     *
     * Calling [plan] twice with the same [PlanningRequest.planningSessionId]
     * throws [IllegalStateException] -- reconsideration requires a new
     * [PlanningRequest], mirroring [TaskProposalIntake]'s own terminal,
     * no-resubmission semantics.
     */
    override suspend fun plan(request: PlanningRequest, candidates: List<PlanCandidate>): PlanningSessionResult {
        mutex.withLock {
            check(request.planningSessionId !in sessions) {
                "PlanningSession '${request.planningSessionId.value}' has already been submitted; " +
                    "reconsideration requires a new PlanningRequest, not resubmitting this one"
            }
            // Tentative reservation -- rolled back below if identity does not resolve, so this
            // Planning Session never appears to have validly entered CREATED at all.
            sessions[request.planningSessionId] = PlannerSessionStatus.CREATED
        }

        if (identityService.resolve(request.initiatingPrincipalId) == null) {
            mutex.withLock { sessions.remove(request.planningSessionId) }
            return PlanningSessionResult.Failed(
                planningSessionId = request.planningSessionId,
                reason = "initiatingPrincipalId '${request.initiatingPrincipalId.value}' does not resolve " +
                    "to a registered Principal",
                rejections = emptyList(),
            )
        }

        publish(
            eventType = "planner.session_created",
            correlationId = request.correlationId,
            payload = mapOf(
                "initiatingPrincipalId" to request.initiatingPrincipalId.value,
                "goal" to request.goal,
            ),
        )

        advance(request.planningSessionId, PlannerSessionStatus.CREATED, PlannerSessionStatus.CONTEXT_GATHERING)
        publish(eventType = "planner.context_requested", correlationId = request.correlationId)

        advance(request.planningSessionId, PlannerSessionStatus.CONTEXT_GATHERING, PlannerSessionStatus.ANALYSING)
        publish(eventType = "planner.analysis_started", correlationId = request.correlationId)

        for (candidate in candidates) {
            publish(
                eventType = "planner.candidate_generated",
                correlationId = request.correlationId,
                payload = mapOf("planCandidateId" to candidate.planCandidateId.value),
            )
        }

        val decision = planDecision.decide(request.goal, candidates)

        return when (decision) {
            is PlanDecisionResult.NoViableCandidate -> {
                publishRejections(decision.rejections, request.correlationId)
                advance(request.planningSessionId, PlannerSessionStatus.ANALYSING, PlannerSessionStatus.FAILED)
                val reason = if (candidates.isEmpty()) {
                    "no Plan Candidates were supplied for this Planning Session"
                } else {
                    "no supplied Plan Candidate was viable (${decision.rejections.size} rejected)"
                }
                publish(
                    eventType = "planner.session_failed",
                    correlationId = request.correlationId,
                    payload = mapOf("reason" to reason),
                )
                PlanningSessionResult.Failed(request.planningSessionId, reason, decision.rejections)
            }

            is PlanDecisionResult.Selected -> {
                publishRejections(decision.rejections, request.correlationId)
                advance(request.planningSessionId, PlannerSessionStatus.ANALYSING, PlannerSessionStatus.PROPOSING)
                publish(
                    eventType = "planner.proposal_created",
                    correlationId = request.correlationId,
                    payload = mapOf("planCandidateId" to decision.winner.planCandidateId.value),
                )

                val taskProposalId = TaskProposalId("${request.planningSessionId.value}-proposal-1")
                val proposal = buildProposal(taskProposalId, decision.winner, request)

                advance(request.planningSessionId, PlannerSessionStatus.PROPOSING, PlannerSessionStatus.SUBMITTED)
                publish(
                    eventType = "planner.proposal_submitted",
                    correlationId = request.correlationId,
                    payload = mapOf("taskProposalId" to taskProposalId.value),
                )

                when (val disposition = taskProposalIntake.submitProposal(proposal)) {
                    is TaskProposalDisposition.Rejected -> {
                        advance(request.planningSessionId, PlannerSessionStatus.SUBMITTED, PlannerSessionStatus.REJECTED)
                        // PlannerRuntimeSpecification.md Section 11's own recorded Open Question:
                        // no dedicated `planner.session_rejected` event exists yet ("still open") --
                        // not invented here.
                        PlanningSessionResult.Rejected(request.planningSessionId, taskProposalId, disposition, decision.rejections)
                    }
                    else -> {
                        // Accepted, Deferred, Split, or Merged: Section 5's own rule is "any
                        // outcome other than every proposal being rejected outright" -> COMPLETED.
                        // This is reading and classifying an already-returned disposition value,
                        // not implementing Deferred/Split/Merged decision logic (out of scope;
                        // see this class's own top-level KDoc).
                        advance(request.planningSessionId, PlannerSessionStatus.SUBMITTED, PlannerSessionStatus.COMPLETED)
                        publish(
                            eventType = "planner.session_completed",
                            correlationId = request.correlationId,
                            payload = mapOf("disposition" to (disposition::class.simpleName ?: "")),
                        )
                        PlanningSessionResult.Completed(request.planningSessionId, taskProposalId, disposition, decision.rejections)
                    }
                }
            }
        }
    }

    private suspend fun publishRejections(rejections: List<PlanRejection>, correlationId: String) {
        for (rejection in rejections) {
            publish(
                eventType = "planner.candidate_rejected",
                correlationId = correlationId,
                payload = mapOf(
                    "planCandidateId" to rejection.planCandidateId.value,
                    "reason" to rejection.reason.name,
                    "detail" to rejection.detail,
                ),
            )
        }
    }

    private suspend fun advance(id: PlanningSessionId, from: PlannerSessionStatus, to: PlannerSessionStatus) {
        PlannerSessionLifecycleTransitions.requireValidTransition(from, to)
        mutex.withLock { sessions[id] = to }
    }

    private fun buildProposal(
        taskProposalId: TaskProposalId,
        candidate: PlanCandidate,
        request: PlanningRequest,
    ): TaskProposal =
        TaskProposal(
            taskProposalId = taskProposalId,
            planningSessionId = request.planningSessionId,
            initiatingPrincipalId = request.initiatingPrincipalId,
            proposedOwnerPrincipalId = request.initiatingPrincipalId,
            goal = candidate.goal,
            source = request.source,
            priority = request.priority,
            constraints = candidate.constraints,
            dependencies = candidate.dependencies,
            requiredCapabilities = candidate.requiredCapabilities,
            expectedOutputs = candidate.expectedOutputs,
            anticipatedPermissionActions = candidate.anticipatedPermissionActions,
            contextReferences = candidate.contextReferences,
            resourceReferences = candidate.resourceReferences,
            rationale = candidate.rationale.ifBlank {
                "Selected Plan Candidate '${candidate.planCandidateId.value}' via DefaultPlanDecision " +
                    "(Sprint 3, Track D, Unit D2): first valid, non-duplicate candidate in generation order."
            },
            riskEstimate = candidate.riskEstimate,
            correlationId = request.correlationId,
        )

    /** Sprint 1, Unit 9 pattern: publishes one `planner.*` [ParkerEvent], with a UUID suffix since several event types fire more than once per Planning Session. */
    private suspend fun publish(eventType: String, correlationId: String, payload: Map<String, String> = emptyMap()) {
        eventBus.publish(
            ParkerEvent(
                eventId = "evt-$correlationId-$eventType-${UUID.randomUUID()}",
                publisherPrincipalId = PLANNER_RUNTIME_PRINCIPAL_ID,
                eventType = EventType(eventType),
                timestamp = Instant.now(),
                correlationId = correlationId,
                payload = payload,
            ),
        )
    }
}
