package parker.core.runtime

import java.nio.ByteBuffer
import java.nio.channels.FileChannel
import java.nio.file.*
import java.security.MessageDigest
import java.time.Instant
import java.util.Base64
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assumptions.assumeTrue
import org.junit.jupiter.api.Test
import parker.composition.OpenAiApiCredential
import parker.core.interfaces.*
import kotlin.io.path.*
import kotlin.test.*

class OrdinaryRequestRegionV8AcceptanceHarnessTest {
    private val enabled=System.getenv("OI10R5_ENABLED")=="true";private val action=System.getenv("OI10R5_ACTION")?:"OFF";private val fixtureName=System.getenv("OI10R5_FIXTURE")
    private val root=Path.of(System.getenv("OI10R5_ACCEPTANCE_ROOT")?:"/home/steve/parker-acceptance/oi10r5-v8-authoritative").toAbsolutePath().normalize()
    private val corpus=Path.of(System.getenv("OI10_CORPUS_ROOT")?:"/tmp/oi10-corpus").toAbsolutePath().normalize();private val codec=OpenAiRequestRegionV8Codec()
    @Test fun `governed OI10R5 v8 acceptance`(){assumeTrue(enabled,"OI10R5 disabled");require(System.getenv("OI10R5_IMPLEMENTATION_COMMIT")==IMPLEMENTATION_COMMIT);require(root!=corpus&&!root.startsWith(Path.of("/mnt/parker-data"))&&!root.startsWith(Path.of("/data")))
        when(action){"PREPARE"->prepareAll();"EXECUTE"->execute(fixture());"REPLAY"->replay(fixture());else->error("unsupported action")}}
    private fun fixture()=FIXTURES.single{it.name==fixtureName}
    private fun prepareAll(){Files.createDirectories(root);FIXTURES.forEach{f->val bytes=corpus.resolve("${f.evidenceId}.evidence").readBytes();require(sha(bytes)==f.sha);val p=prepare(f,bytes);val d=root.resolve(f.name);Files.createDirectories(d);create(d.resolve("source.pdf"),bytes);val crops=d.resolve("crops");Files.createDirectories(crops);p.request.regions.forEachIndexed{i,r->create(crops.resolve("%02d-%s.png".format(i+1,r.id.value)),r.image.encodedBytes())};create(d.resolve("manifest.json"),envelope(manifest(f,p)));create(d.resolve("authority.json"),envelope(authority(f,p)));println("OI10R5_PREPARED=${f.name} sourceRegions=${p.graphs.sumOf{it.regions.size}} requests=${p.request.regions.size} body=${p.body.length} requestDigest=${codec.requestDigest(p.request)} manifestDigest=${sha(p.body.toByteArray())}")}}
    private fun execute(f:Fixture){val p=load(f);val d=root.resolve(f.name);verify(d,f,p);require(FIXTURES.all{root.resolve(it.name).resolve("authority.json").exists()&&root.resolve(it.name).resolve("manifest.json").exists()});val ordinal=FIXTURES.indexOf(f);require(FIXTURES.take(ordinal).all{root.resolve(it.name).resolve("assessment.json").exists()});require(FIXTURES.drop(ordinal).all{!root.resolve(it.name).resolve("attempt.json").exists()});require(!d.resolve("attempt.json").exists()&&!d.resolve("response.json").exists());require(FIXTURES.count{root.resolve(it.name).resolve("attempt.json").exists()}<3);@Suppress("UNCHECKED_CAST") val wire=RegionJson.parse(p.body) as Map<String,Any?>;require(wire["model"]==REQUEST_REGION_MODEL&&wire["store"]==false&&wire["stream"]==false&&wire["reasoning"]==mapOf("effort" to "none"))
        create(d.resolve("attempt.json"),envelope(linkedMapOf("format" to "oi10r5-v8-attempt-v1","fixture" to f.name,"request_digest" to codec.requestDigest(p.request),"state" to "PROVIDER_ATTEMPT_STARTED","implementation_commit" to IMPLEMENTATION_COMMIT,"started_at" to Instant.now().toString(),"maximum_fixture_attempts" to 1,"maximum_total_attempts" to 3,"retries" to 0)))
        val credential=OpenAiApiCredential.fromEnvironment(System.getenv("PARKER_OPENAI_API_KEY"))?:error("credential absent");val response=runBlocking{JdkOpenAiResponsesTransport().execute(OpenAiResponsesTransportRequest(java.net.URI("https://api.openai.com/v1/responses"),300_000,p.body,20L*1024*1024,credential))}
        create(d.resolve("response.json"),envelope(linkedMapOf("format" to "oi10r5-v8-raw-response-v1","fixture" to f.name,"request_digest" to codec.requestDigest(p.request),"http_status" to response.statusCode,"received_at" to Instant.now().toString(),"raw_length" to response.body.size,"raw_sha256" to sha(response.body),"raw_base64" to Base64.getEncoder().encodeToString(response.body))));require(response.statusCode in 200..299)
        val parsed=parse(p.request,response.body);val derivative=RequestRegionV8DerivativeBinder().bind(p.request,parsed.result).getOrThrow();create(d.resolve("assessment.json"),envelope(assessment(f,p,parsed,derivative)));println("OI10R5_EXECUTED=${f.name} response=${parsed.id} raw=${sha(response.body)} blocks=${derivative.blocksInParkerOrder.size}")}
    private fun replay(f:Fixture){val p=load(f);val d=root.resolve(f.name);verify(d,f,p);val raw=record(d.resolve("response.json"));val bytes=Base64.getDecoder().decode(raw["raw_base64"] as String);require(sha(bytes)==raw["raw_sha256"]);val parsed=parse(p.request,bytes);val derivative=RequestRegionV8DerivativeBinder().bind(p.request,parsed.result).getOrThrow();require(RegionJson.encode(record(d.resolve("assessment.json")))==RegionJson.encode(assessment(f,p,parsed,derivative)));println("OI10R5_REPLAY=${f.name} raw=${sha(bytes)} canonical=${derivative.canonicalDigest} PASS")}
    private data class Parsed(val id:String,val model:String,val structured:Map<String,Any?>,val result:RequestRegionV8Result)
    private fun parse(request:RequestRegionV8Request,bytes:ByteArray):Parsed{@Suppress("UNCHECKED_CAST") val e=RegionJson.parse(bytes.toString(Charsets.UTF_8)) as Map<String,Any?>;val id=e["id"] as String;val model=e["model"] as String;require(model==REQUEST_REGION_MODEL);@Suppress("UNCHECKED_CAST") val output=e["output"] as List<Map<String,Any?>>;@Suppress("UNCHECKED_CAST") val content=output.single{it["type"]=="message"}["content"] as List<Map<String,Any?>>;val text=content.single{it["type"]=="output_text"}["text"] as String;@Suppress("UNCHECKED_CAST") val structured=RegionJson.parse(text) as Map<String,Any?>;val valid=RequestRegionV8StructuredValidator().validate(request,structured) as? RequestRegionV8ValidationOutcome.Valid?:error("v8 validation rejected");return Parsed(id,model,structured,valid.result)}
    private data class Fixture(val name:String,val evidenceId:String,val sha:String,val role:String)
    private data class Prepared(val request:RequestRegionV8Request,val pages:List<AuthoritativePageRepresentation>,val graphs:List<SourceRegionOrderGraph>,val body:String)
    private fun load(f:Fixture)=prepare(f,root.resolve(f.name).resolve("source.pdf").readBytes())
    private fun prepare(f:Fixture,bytes:ByteArray):Prepared{
        require(sha(bytes)==f.sha)
        val renderer=DeterministicSourcePageRenderer()
        val deriver=DeterministicSourceRegionDeriver()
        val profile=PageRenderProfile("authoritative-page-region-raster-v1",1,300)
        fun page(n:Int)=assertIs<SourcePageRepresentationOutcome.Created>(renderer.render(SourcePageRenderRequest(EvidenceArtifactId(f.evidenceId),f.sha,"application/pdf",bytes,n,profile))).representation
        val first=page(1)
        val pages=(1..first.provenance.declaredPageCount).map{if(it==1)first else page(it)}
        val graphs=pages.map{assertIs<SourceRegionDerivationOutcome.Derived>(deriver.derive(it)).graph}
        val shaped=assertIs<RequestRegionShapingOutcome.Shaped>(DeterministicCompleteSetRequestRegionShaper(renderer).shape(pages,graphs))
        val request=RequestRegionV8Request("oi10r5-v8-${f.name.lowercase()}-acceptance",shaped.regions)
        return Prepared(request,pages,graphs,codec.buildRequestBody(request))
    }
    private fun manifest(f:Fixture,p:Prepared)=linkedMapOf<String,Any?>("fixture" to f.name,"role" to f.role,"evidence_id" to f.evidenceId,"source_sha256" to f.sha,"pages" to p.pages.size,"source_region_count" to p.graphs.sumOf{it.regions.size},"request_region_count" to p.request.regions.size,"request_region_ids" to p.request.regions.map{it.id.value},"bounds" to p.request.regions.map{listOf(it.bounds.left,it.bounds.top,it.bounds.rightExclusive,it.bounds.bottomExclusive)},"memberships" to p.request.regions.map{it.constituentIds.map(SourceRegionId::value)},"request_digest" to codec.requestDigest(p.request),"body_bytes" to p.body.toByteArray().size,"body_manifest_digest" to sha(p.body.toByteArray()),"review" to "AUTHORITATIVE_CROP_VISUAL_LITERAL_UNCERTAINTY_PROVENANCE")
    private fun authority(f:Fixture,p:Prepared)=linkedMapOf<String,Any?>("authority_id" to "authority-ordinary-ingestion-10r5-v8-${f.name.lowercase()}","fixture" to f.name,"capability_id" to ORDINARY_REQUEST_REGION_V8_CAPABILITY_ID,"capability_digest" to OrdinaryRequestRegionV8Capability().digest(),"lifecycle" to "ACCEPTANCE_PENDING","implementation_commit" to IMPLEMENTATION_COMMIT,"harness_commit" to requireNotNull(System.getenv("OI10R5_EXPECTED_HEAD")).also{require(it.matches(Regex("^[0-9a-f]{40}$")))},"provider" to REQUEST_REGION_PROVIDER,"model" to REQUEST_REGION_MODEL,"endpoint" to "https://api.openai.com/v1/responses","reasoning" to "none","store" to false,"profile" to REQUEST_REGION_V8_PROFILE_ID,"schema" to REQUEST_REGION_V8_SCHEMA_ID,"wire" to 8,"adapter_version" to REQUEST_REGION_V8_ADAPTER_VERSION,"parser_version" to REQUEST_REGION_V8_PARSER_VERSION,"processing" to REQUEST_REGION_V8_PROCESSING_PROFILE,"instruction_digest" to REQUEST_REGION_V8_INSTRUCTION_SHA256,"schema_digest" to REQUEST_REGION_V8_SCHEMA_SHA256,"shaping" to REQUEST_REGION_SHAPING_ID,"maximum_requests" to 32,"maximum_body_bytes" to REQUEST_REGION_BODY_MAXIMUM_BYTES,"maximum_calls" to 3,"maximum_fixture_calls" to 1,"retries" to 0,"request_digest" to codec.requestDigest(p.request))
    private fun assessment(f:Fixture,p:Prepared,x:Parsed,d:RequestRegionV8Derivative)=linkedMapOf<String,Any?>("format" to "oi10r5-v8-assessment-v1","fixture" to f.name,"request_digest" to codec.requestDigest(p.request),"response_id" to x.id,"model" to x.model,"structured_sha256" to sha(RegionJson.encode(x.structured).toByteArray()),"canonical_digest" to d.canonicalDigest,"parker_order" to d.blocksInParkerOrder.map{it.requestRegionId},"memberships" to d.blocksInParkerOrder.map{it.constituentSourceRegionIds},"result" to "STRUCTURAL_PASS_FIDELITY_REVIEW_PENDING")
    private fun verify(d:Path,f:Fixture,p:Prepared){require(RegionJson.encode(record(d.resolve("manifest.json")))==RegionJson.encode(manifest(f,p)));if(f.name=="B"){require(p.graphs.map{it.regions.size}==listOf(16,14,6));require(p.request.regions.groupingBy{it.pageNumber}.eachCount().toSortedMap().values.toList()==listOf(14,12,6));require(codec.requestDigest(p.request)=="a5ef4672e07493ae870cc798fe24a87651ffc007446e40716f48ea5e62356d03");require(sha(p.body.toByteArray())=="8bf1c47066c6c13bd2a72757712ceebe5497b3929153b0c5befc0a56c362690a")}}
    private fun envelope(r:Map<String,Any?>):ByteArray=RegionJson.encode(linkedMapOf("record" to r,"record_sha256" to sha(RegionJson.encode(r).toByteArray()))).toByteArray();@Suppress("UNCHECKED_CAST") private fun record(p:Path):Map<String,Any?>{val e=RegionJson.parse(p.readText()) as Map<String,Any?>;val r=e["record"] as Map<String,Any?>;require(e["record_sha256"]==sha(RegionJson.encode(r).toByteArray()));return r}
    private fun create(p:Path,b:ByteArray){require(!p.exists());FileChannel.open(p,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE).use{c->val x=ByteBuffer.wrap(b);while(x.hasRemaining())c.write(x);c.force(true)}}
    private fun sha(b:ByteArray)=MessageDigest.getInstance("SHA-256").digest(b).joinToString(""){"%02x".format(it.toInt()and 255)}
    companion object{const val IMPLEMENTATION_COMMIT="18b81a6d7834cb19e1ad884dbcc40a22289af288";private val FIXTURES=listOf(Fixture("A","evidence-28c076ae-0666-45ef-a04e-297d74a639c9","64039b3200b34c67ce1f993c1cb1f98a115390d6aa25541ceb8a60e674441149","singleton"),Fixture("B","evidence-4c6f2ee8-2f62-47be-bd7a-946c744b2766","ce8bd4b53d8b007026575974014e71f648f045bf3970b0e984605cf842a7b4a5","sprint2"),Fixture("C","evidence-0275472f-535a-4cf1-b30d-f45ac7684743","7373ad403b4fae5bf5c777deb8524eaa3ba38594ce9fabfa8fcbce22fbd33182","source_order"))}
}
